### ISSUE TITLE
Infinity Loop. in remill-lift.

### ISSUE THREAD

**Issue by dbwodlf3** [lifting-bits/remill#449]
Hello.

I am trying some examples in remill-lift.

i tried this(jump self instruction...).
```bash
remill-lift-9.0 --os linux --arch x86 --bytes ebfe --ir_out /dev/stdout
```
and i tried some infinity loop examples.

the results are same. like this.
```
; Function Attrs: noinline noreturn nounwind
define noalias nonnull %struct.Memory* @sub_0(%struct.State* noalias nocapture dereferenceable(3376), i32, %struct.Memory* noalias) local_unnamed_addr #0 {
  br label %4

; <label>:4:                                      ; preds = %4, %3
  br label %4
}
```
remill-lift doesn't lift..

I don't know why.

**Comment by dbwodlf3** [comment]
I think this error occurs  because of optimization.
https://github.com/lifting-bits/remill/blob/master/tools/lift/Lift.cpp#L271
https://github.com/lifting-bits/remill/blob/master/tools/lift/Lift.cpp#L423

I think it is better to select optimization by option. (like clang option -O0)

If i can solve this problem(?), i will sent PR...

**Comment by pgoodman** [comment]
I think I'm having trouble understanding what the problem is. What is the bitcode that you're expecting from this? As far as I can tell, you did the following:

```
foo:
    jmp foo
```

This is an infinite loop, and it seems like remill has lifted it as such. The target program counter matches the input program counter, so no registers in the `State` structure need to change, hence why those have likely been optimized away.

![image](https://user-images.githubusercontent.com/43664/94308334-5bba0c80-ff44-11ea-90a1-8d2178a599d6.png)

**Comment by dbwodlf3** [comment]
optimizing make many problems than i thought.
.y.

**Comment by dbwodlf3** [comment]
Sorry... it doesn't a bug. it works. just my misunderstanding.
